### ISSUE TITLE
Как запустить?

### ISSUE THREAD

**Issue by Noneeer** [REDxEYE/VK_BOT#1]
Какие модули нужно установить? Какая версия питона нужна?

**Comment by REDxEYE** [comment]
Python 3.5+ 
Модулей там куча нужна. Как будет время напишу полную документацию.
А в данный момент предлагаю перебраться в вк для уточнения всех деталей. 
Стучаться вот [сюда](https://vk.com/red_eye_rus) с пометкой GITHUB

**Comment by fixator10** [comment]
![image](https://user-images.githubusercontent.com/11073934/40972002-5e8af300-68d0-11e8-80ab-772d2486e26c.png)

**Comment by REDxEYE** [comment]
Проект уже как 2 года заброшен в плане разработки. Недавно только пофиксил ошибку и всё
